# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: operator.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eoperator.proto\" \n\nIsPossible\x12\x12\n\nIsPossible\x18\x01 \x01(\x08\"\x1d\n\x07tempvar\x12\x12\n\ntempString\x18\x01 \x01(\t\"\'\n\x13NumeroAdministrador\x12\x10\n\x08NumAdmin\x18\x01 \x01(\x05\"#\n\x0eVerificarConta\x12\x11\n\tExistente\x18\x01 \x01(\x08\"6\n\x08Operador\x12\x14\n\x0cNameOperador\x18\x01 \x01(\t\x12\x14\n\x0cPalavraPasse\x18\x02 \x01(\t\"x\n\nInstalacao\x12\x11\n\tnum_Admin\x18\x01 \x01(\t\x12\x11\n\tDomicilio\x18\x02 \x01(\t\x12\x12\n\nTecnologia\x18\x03 \x01(\t\x12\x12\n\nModalidade\x18\x04 \x01(\t\x12\x0e\n\x06\x45stado\x18\x05 \x01(\t\x12\x0c\n\x04\x44\x61ta\x18\x06 \x01(\t\"Y\n\x0eOperadorPerfil\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x14\n\x0cNomeOperador\x18\x02 \x01(\t\x12\x14\n\x0cPalavraPasse\x18\x03 \x01(\t\x12\x0f\n\x07IsAdmin\x18\x04 \x01(\x08\x32\xf2\x04\n\x08Operator\x12*\n\x0fReturnAllInstal\x12\x08.tempvar\x1a\x0b.Instalacao0\x01\x12\x30\n\x11ReturnAllOperador\x12\x08.tempvar\x1a\x0f.OperadorPerfil0\x01\x12*\n\x0c\x41\x63\x63ountExist\x12\t.Operador\x1a\x0f.VerificarConta\x12\x35\n\x17\x41\x63\x63outnExistOperadorExt\x12\t.Operador\x1a\x0f.VerificarConta\x12\x34\n\x0fReservaPossible\x12\x0b.Instalacao\x1a\x14.NumeroAdministrador\x12\x35\n\x10\x41tivacaoPossible\x12\x14.NumeroAdministrador\x1a\x0b.IsPossible\x12\x38\n\x13\x44\x65sativacaoPossible\x12\x14.NumeroAdministrador\x1a\x0b.IsPossible\x12\x37\n\x12TerminacaoPossible\x12\x14.NumeroAdministrador\x1a\x0b.IsPossible\x12\x30\n\x10\x45liminarOperador\x12\x0f.OperadorPerfil\x1a\x0b.IsPossible\x12\x31\n\x11\x41\x64icionarOperador\x12\x0f.OperadorPerfil\x1a\x0b.IsPossible\x12/\n\x0fOperadorToAdmin\x12\x0f.OperadorPerfil\x1a\x0b.IsPossible\x12/\n\x0f\x41\x64minToOperador\x12\x0f.OperadorPerfil\x1a\x0b.IsPossibleB\x0f\xaa\x02\x0cServidorGRPCb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'operator_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\252\002\014ServidorGRPC'
  _ISPOSSIBLE._serialized_start=18
  _ISPOSSIBLE._serialized_end=50
  _TEMPVAR._serialized_start=52
  _TEMPVAR._serialized_end=81
  _NUMEROADMINISTRADOR._serialized_start=83
  _NUMEROADMINISTRADOR._serialized_end=122
  _VERIFICARCONTA._serialized_start=124
  _VERIFICARCONTA._serialized_end=159
  _OPERADOR._serialized_start=161
  _OPERADOR._serialized_end=215
  _INSTALACAO._serialized_start=217
  _INSTALACAO._serialized_end=337
  _OPERADORPERFIL._serialized_start=339
  _OPERADORPERFIL._serialized_end=428
  _OPERATOR._serialized_start=431
  _OPERATOR._serialized_end=1057
# @@protoc_insertion_point(module_scope)
